FROM python:3.9-slim-buster

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        curl \
        build-essential \ 
        libpq-dev

RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

ENV PATH="${PATH}:/root/.poetry/bin"

WORKDIR /app
COPY alembic/ /app/alembic/
COPY poetry.lock pyproject.toml alembic.ini /app/
RUN poetry install --no-dev

CMD ["poetry", "run", "uvicorn", "todo.main:app", "--host", $app_host, "--port", $app_port, "--reload"]
