version: '3.4'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes: 
      - ./data/db:/var/lib/postgresql/data
  api:
    depends_on:
      - postgres
    env_file:
      - .env
    image: todoapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes: 
      - ./todo:/app/todo
  nginx: 
    depends_on:
      - api
    env_file:
      - .env
    image: nginx
    ports: 
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${NGINX_SSL_PORT}:${NGINX_SSL_PORT}
    volumes:
      - ./templates:/etc/nginx/templates
      - ./certs:/etc/nginx/certs
