version: '3.4'

services:
  api:
    image: todoapi
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes: 
      - ./todo:/app/todo
  db:
    image: postgres
  cache:
    image: "redis:alpine"
