version: '3.4'

services:
  postgres:
    image: postgres
    env_file:
      - .env.prod
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes: 
      - ./data/db:/var/lib/postgresql/data
  api:
    depends_on:
      - postgres
    env_file:
      - .env.prod
    image: todoapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes: 
      - ./todo:/app/todo
  nginx: 
    depends_on:
      - api
    env_file:
      - .env.prod
    image: nginx
    ports: 
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${NGINX_SSL_PORT}:${NGINX_SSL_PORT}
    volumes:
      - ./conf/prod/templates:/etc/nginx/templates
      - ./conf/prod/certbot/www:/var/www/certbot/:ro
      - ./conf/prod/certbot/conf/:/etc/nginx/certs/:ro
  certbot:
    env_file:
      - .env.prod
    image: certbot/certbot:latest
    volumes:
      - ./conf/prod/certbot/www/:/var/www/certbot/:rw
      - ./conf/prod/certbot/conf/:/etc/letsencrypt/:rw