version: '3.4'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports: 
      - 5432:5432
    volumes: 
      - ./data/db:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    env_file:
      - .env
  api:
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    image: todoapi
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes: 
      - ./todo:/app/todo
