version: "3.4"

services:
    postgres:
        image: postgres
        env_file:
            - .env
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./data/db:/var/lib/postgresql/data
    api:
        depends_on:
            - postgres
        env_file:
            - .env
        image: todoapi
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - ${APP_PORT}:${APP_PORT}
        volumes:
            - ./todo:/app/todo
