version: "3.4"

services:
    postgres:
        image: postgres
        env_file:
            - .env.prod
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./data/db:/var/lib/postgresql/data
    api:
        depends_on:
            - postgres
        env_file:
            - .env.prod
        image: ${DOCKER_REGISTRY}/todoapi
        ports:
            - ${APP_PORT}:${APP_PORT}
