name: scp files
on:
    push:
        branches:
            - main
env:
    REACT_APP_API_URL: ${{ secrets.API_URL }}
jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Bucket actions
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: npm install
            - run: npm run build
            - name: publish files using scp
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY}}
                  port: ${{ secrets.PORT }}
                  overwrite: true
                  source: "./build/*"
                  strip_components: 1
                  target: "~/apps/todo-client"
