name: Deploy changes
on:
    push:
        branches:
            - main
env:
    REACT_APP_API_URL: ${{ secrets.API_URL }}
jobs:
    deploy_backend:
        name: "Build and Push to ECR"
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
              with:
                  mask-password: "true"
            - name: Build, tag, and push image to Amazon ECR 🏷
              id: build-image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  IMAGE_TAG: todoapi
              run: |
                  docker build -t $ECR_REGISTRY/${{ secrets.ECR_REPO }}:$IMAGE_TAG .
                  docker push $ECR_REGISTRY/${{ secrets.ECR_REPO }}:$IMAGE_TAG
                  echo "::set-output name=image:$ECR_REGISTRY/${{ secrets.ECR_REPO }}:$IMAGE_TAG"
