name: Deploy changes
on:
    push:
        branches:
            - main
env:
    REACT_APP_API_URL: ${{ secrets.API_URL }}
jobs:
    deploy_client:
        name: Build and deploy client
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - uses: actions/checkout@master
            - name: Bucket actions
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: npm install
            - run: npm run build
            - name: publish files using scp
              uses: appleboy/scp-action@@v0.1.4
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  overwrite: true
                  source: "./build/*"
                  strip_components: 1
                  target: "~/apps/todo-client"
    deploy_backend:
        name: Build and push docker image
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Build image
              run: docker build ./backend/ -t todoapi
            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
            - name: Log in to DO Container Registry
              run: doctl registry login --expiry-seconds 600
            - name: Tag image
              run: docker tag todoapi ${{ secrets.DOCKER_REGISTRY }}/todoapi
            - name: Push image to DO Container Registry
              run: docker push ${{ secrets.DOCKER_REGISTRY }}/todoapi
